COMMON_SKILLS = {
    "python",
    "java",
    "c++",
    "c#",
    "sql",
    "mysql",
    "postgresql",
    "mongodb",
    "sqlite",
    "aws",
    "azure",
    "gcp",
    "docker",
    "kubernetes",
    "linux",
    "git",
    "github",
    "rest api",
    "microservices",
    "fastapi",
    "flask",
    "django",
    "streamlit",
    "pandas",
    "numpy",
    "scikit-learn",
    "tensorflow",
    "pytorch",
    "nlp",
    "machine learning",
    "deep learning",
    "data analysis",
    "data science",
    "data engineering",
    "airflow",
    "spark",
    "hadoop",
    "tableau",
    "power bi",
    "excel",
    "html",
    "css",
    "javascript",
    "typescript",
    "react",
    "node.js",
    "node",
    "ci/cd",
    "jenkins",
    "pytest",
    "unit testing",
    "agile",
    "scrum",
    "communication",
    "leadership",
    "langchain",
    "llm",
    "openai",
    "gemini",
    "prompt engineering",
    "vector database",
    "faiss",
    "pinecone",
    "redis",
    "etl",
    "api development",
    "problem solving",
}

DEGREE_KEYWORDS = {
    "bachelor",
    "bachelors",
    "master",
    "masters",
    "phd",
    "doctorate",
    "b.tech",
    "m.tech",
    "b.e",
    "m.e",
    "b.sc",
    "m.sc",
    "bca",
    "mca",
    "mba",
}

SUPPORTED_EXTENSIONS = (".pdf", ".docx", ".txt")
